# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f64cd82a4dc3bae04e704c4bc0986dd69934b614e5853deb30f065f8df57caf9653f588d1be443a933f38f7b766470dc99fba9a67652f5c439afd73555e82fc6

test:
  secret_key_base: 7d11ac6fc198b4f4905bd2fef31d9e2dd839952f5fa4a1ba841d0e840930bfb150e471cd5c7477806792397adbe3f6a2b111103ca2ea2f9332e412dff21d766d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
